# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('resources', 'resources'),
    ],
    hiddenimports=[
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
        'app',
        'app.application',
        'app.config',
        'core',
        'core.drawing_engine',
        'core.notebook',
        'core.page',
        'core.stroke',
        'core.commands',
        'core.commands.add_stroke',
        'core.commands.delete_stroke',
        'core.commands.move_stroke',
        'core.commands.command_manager',
        'core.tools',
        'core.tools.pen',
        'core.tools.eraser',
        'core.tools.highlighter',
        'core.tools.selection',
        'storage',
        'storage.json_store',
        'storage.document_store',
        'ui',
        'ui.main_window',
        'ui.canvas_widget',
        'ui.toolbar',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='BetterNote',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['resources/icons/app_icon.ico'],
)

